Boilerplate imports

In [3]:
import  numpy  as  np
from  datascience  import *
%matplotlib inline
import matplotlib.pyplot as plts
plts.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

In [35]:
about_me=np.array(['Luke','Barger','Washington','Green'])
about_me

array(['Luke', 'Barger', 'Washington', 'Green'], dtype='<U10')

Mall uppercase

In [36]:
about_me_upper=np.char.upper(about_me)
about_me_upper

array(['LUKE', 'BARGER', 'WASHINGTON', 'GREEN'], dtype='<U10')

Count times 'a' appears in each element array

In [37]:
np.char.count(about_me,'a')

array([0, 1, 1, 0])

Count length of each string in array

In [38]:
lengths = []
for i in about_me:
    lengths.append(len(i))

print(lengths)

[4, 6, 10, 5]


Creat an array containing every other odd numer starting with 1 and ending with (and including) 41

In [43]:
odds=np.arange(1,42,4)
odds

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

Convert to floats

In [51]:
odds_fl=odds.astype(float)

Find the sum and product of all elements in the array

In [65]:
odds_sum=np.sum(odds_fl)
odds_prod=np.prod(odds_fl)
print('The sum is',int(odds_sum),'.')
print('The product is',format(odds_prod,".3e"),'.')

The sum is 231 .
The product is 7.580e+12 .


natural log of each element

In [58]:
np.log(odds_fl)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

Find the difference and sum of  adjacent elements

In [68]:
np.diff(odds_fl)

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [83]:
adj_sums = []
for i in range(len(odds_fl)-1):
    adj_sums.append(odds_fl[i]+odds_fl[i+1])

print(adj_sums)

[6.0, 14.0, 22.0, 30.0, 38.0, 46.0, 54.0, 62.0, 70.0, 78.0]
